### ISSUE TITLE
After the rewrite (#1), there is no longer support for --flag=value

### ISSUE THREAD

**Issue by quittle** [quittle/ahoy#2]
A number of command line tools accept both `--flag value` and `--flag=value`. This is a common and expected thing and should be supported

**Comment by bschlenk** [comment]
It is much more common for the short version of a flag not to require an equals, e.g. `-f value`, and the long version to require an equals, e.g. `—flag=value`. Not requiring an equals for long flags is a minor convenience some tools/parsers have decided to support.

**Comment by quittle** [comment]
Can you provide some examples of tools that require equals for long forms but short forms to not?

**Comment by bschlenk** [comment]
Never mind, I guess I just never tried leaving it off. I must have been thinking of short keys allowing values directly next to the key, but long keys not.
